# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import trading_pb2 as trading__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in trading_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TradingServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckOrder = channel.unary_unary(
                '/trading.TradingService/CheckOrder',
                request_serializer=trading__pb2.CheckOrderRequest.SerializeToString,
                response_deserializer=trading__pb2.CheckOrderResponse.FromString,
                _registered_method=True)
        self.UpdateState = channel.unary_unary(
                '/trading.TradingService/UpdateState',
                request_serializer=trading__pb2.UpdateStateRequest.SerializeToString,
                response_deserializer=trading__pb2.UpdateStateResponse.FromString,
                _registered_method=True)
        self.LoadUser = channel.unary_unary(
                '/trading.TradingService/LoadUser',
                request_serializer=trading__pb2.LoadUserRequest.SerializeToString,
                response_deserializer=trading__pb2.LoadUserResponse.FromString,
                _registered_method=True)
        self.GetPrice = channel.unary_unary(
                '/trading.TradingService/GetPrice',
                request_serializer=trading__pb2.GetPriceRequest.SerializeToString,
                response_deserializer=trading__pb2.GetPriceResponse.FromString,
                _registered_method=True)
        self.GetAllPrices = channel.unary_unary(
                '/trading.TradingService/GetAllPrices',
                request_serializer=trading__pb2.GetAllPricesRequest.SerializeToString,
                response_deserializer=trading__pb2.GetAllPricesResponse.FromString,
                _registered_method=True)


class TradingServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CheckOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllPrices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TradingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckOrder,
                    request_deserializer=trading__pb2.CheckOrderRequest.FromString,
                    response_serializer=trading__pb2.CheckOrderResponse.SerializeToString,
            ),
            'UpdateState': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateState,
                    request_deserializer=trading__pb2.UpdateStateRequest.FromString,
                    response_serializer=trading__pb2.UpdateStateResponse.SerializeToString,
            ),
            'LoadUser': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadUser,
                    request_deserializer=trading__pb2.LoadUserRequest.FromString,
                    response_serializer=trading__pb2.LoadUserResponse.SerializeToString,
            ),
            'GetPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrice,
                    request_deserializer=trading__pb2.GetPriceRequest.FromString,
                    response_serializer=trading__pb2.GetPriceResponse.SerializeToString,
            ),
            'GetAllPrices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllPrices,
                    request_deserializer=trading__pb2.GetAllPricesRequest.FromString,
                    response_serializer=trading__pb2.GetAllPricesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trading.TradingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trading.TradingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TradingService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.TradingService/CheckOrder',
            trading__pb2.CheckOrderRequest.SerializeToString,
            trading__pb2.CheckOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.TradingService/UpdateState',
            trading__pb2.UpdateStateRequest.SerializeToString,
            trading__pb2.UpdateStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.TradingService/LoadUser',
            trading__pb2.LoadUserRequest.SerializeToString,
            trading__pb2.LoadUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.TradingService/GetPrice',
            trading__pb2.GetPriceRequest.SerializeToString,
            trading__pb2.GetPriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllPrices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trading.TradingService/GetAllPrices',
            trading__pb2.GetAllPricesRequest.SerializeToString,
            trading__pb2.GetAllPricesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
